// ===================================================================
include::attributes-generic.adoc[]
include::attributes-product-micro.adoc[]
// START ARCH-INDEPENDENT
=== {Cockpit} web-based node management system
For web-based management of a single node, {Cockpit} is included. For details, refer to https://documentation.suse.com/sle-micro/6.0/html/SLE-Micro-all/article-administration-slemicro.html#sec-admin-{cockpit}.

There have been new {cockpit} modules added to the product. Due to the amount of dependencies, not all of the {Cockpit} modules are part of the raw images and some have to be installed additionally.

When enabling a firewall via the {Cockpit} user interface, be aware that your connection to the host may be interrupted unless the {Cockpit} port is configured to be open in advance.

The {SELinux} module for {Cockpit} provides basic functionality for users to troubleshoot their configuration. With this release the functionality has been extended with the introduction of the setroubleshoot-server package.
