include::attributes-generic.adoc[]

[#Installation-micro]
== Installation

=== Installation media
* Image based deployment images
** Base OS Image (Base OS + podman only)
*** Plus QCOW version of this image (x86_64, aarch64. S390x)
*** Plus VMware (VMDK) version of this image (x86_64)
** OS image (Base OS, salt-minion, KVM + libvirt packages)
*** Plus QCOW version of this image (x86_64, aarch64. S390x)
*** Plus VMware (VMDK) version of this image (x86_64)
** OS image with RT kernel (x86_64 only), no KVM support on this image
** Base OEM image – self-installation image (Base OS + podman only) for x86_64
** OEM image – self-installation image (Base OS, salt-minion, KVM + libvirt packages) for x86_64
** OEM image with RT kernel – self-installation image, no KVM support on this image for x86_64

Images other than QCOW or VMDK target bare metal deployments.

=== Additional Container Images
* SUSE Toolbox container for debugging, based on current SLE15 SP, provided via Registry.suse.com
* PCP container image (unmodified)

=== High-Level Requirements
Use of SLE Micro without a container runtime is only supported when SLE Micro is used as a KVM host and workloads are installed into KVM virtual machines.
Running workloads directly on the OS is not supported, with the exception of system management software.

=== Installation Modes

SUSE Linux Enterprise Micro 6.0 only supports deployment via images. An installer based installation method is not offered.

Customization of the installation process with the provided images can be done with Ignition and Combustion (pre-configured images and self-installing images).

We will offer select images with support for cloud-init with a later milestone.

=== Supported Architectures

* Intel/AMD 64bit (x86_64)
* ARM 64bit (aarch64)
* IBM Z (s390x)

=== Upgrade Path
An online migration of existing SLE Micro 5.5 installations to SLE Micro 6.0 is possible and is fully supported. Upgrading from SUSE Linux Enterprise Micro 5.5 is only possible via the transactional-update tool.
For the upgrade procedure, refer to https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/book-upgrade.html

=== Change in installation methods

With previous releases we supported manual installation via a YaST based image.
With SLE Micro 6.0 we have dropped support for this installation method and only focus on RAW
image based deployments.
The SelfInstall image variant has been extended to allow setting of various parameters to direct it and also enable an unattended installation using the SelfInstall image.

=== Installing SUSE Linux Enterprise Micro
==== Unattended installation with Yomi (technology preview)
To learn how to install a system with Yomi, see the SUSE Manager documentation, section Install using Yomi.
Installation with Yomi is a technology preview.

==== Deploying pre-built images
SUSE Linux Enterprise Micro is provided as raw images which can be deployed directly to a storage device, for example, a memory card, a USB stick, or a hard drive.
SUSE Linux Enterprise Micro is also provided as images for specific hardware device with a customized software selection.

For a procedure of deploying an image refer to https://documentation.suse.com/sle-micro/5.5/html/SLE-Micro-all/part-raw-image.html

In addition to media provided by SUSE Linux Enterprise Micro 5.4, this release includes qcow2 images for  aarch64 and x86_64.
