// ===================================================================
include::attributes-generic.adoc[]
include::attributes-product-micro.adoc[]
// START ARCH-INDEPENDENT
=== {Podman} upgrade from 4.3.X. to 4.7.1
{Podman} 4.7 is a major release with tons of new features and extensive bug fixes compared to {Podman} 4.3. Individual changes are to be found upstream https://github.com/containers/podman/blob/main/RELEASE_NOTES.md

{Podman} 4.x brings a new container network stack based on Netavark, the new container network stack and Aardvark DNS server in addition to the existing container network interface (CNI) stack used by {Podman} 3.x .The new stack brings 3 important improvement:

* Better support for containers in multiple networks
* Better IPv6 support
* Better performance

To ensure that nothing breaks with this major change, the old CNI stack will remain the default on existing installations. Bear in mind that Netavark will be released as part of a maintenance update.
==== Warning
Before testing {Podman} 4 and the new network stack, you will have to destroy all your current containers, images, and networks.
You must export/save any import containers or images on a private registry, or make sure that your Dockerfiles are available for rebuilding and scripts/playbooks/states to reapply any settings, regenerate secrets, etc.

If you have run {Podman} 3.x before upgrading to {Podman} 4, {Podman} will continue to use CNI plugins as it had before.
To begin using {Podman} 4 with Netavark, you need to run the command podman system reset.\
The command will destroy all images, networks and all containers.

For a complete overview of the changes, please check out the upstream 4.0.0 but also 4.1.1, 4.2.0 and 4.3.0 to be informed about all the new features and changes.
