// ===================================================================

// START ARCH-INDEPENDENT
[#what-is-sle-micro]
== What is SUSE Linux Enterprise Micro?
SUSE Linux Enterprise Micro 6.0 (SLE Micro 6.0) is a modern operating system primarily targeted for edge computing.
It is an ultra-reliable, lightweight operating system purpose built for containerized and virtualized workloads.
It leverages the enterprise hardened security and compliance components of SUSE Linux Enterprise and merges them with a modern, immutable, developer-friendly OS platform.

SUSE Linux Enterprise Micro 6.0 will build upon the momentum generated by the previous Releases.
SLE Micro 6.0 is based on new code base, enhanced with select features based on customer and partner requests, as well as internal feedback.
The focus is migrating to the new code base ensuring a smooth migration for existing customers.

=== Predictability
By the means of using a read-only root-filesystem, SLE Micro ensures the operating system cannot be altered during runtime and therefore consistently run the same artifacts after every reboot.

=== Scalability
SLE Micro will remove efforts to configure individual instances during runtime.
It can be rolled out repeatedly with a predictable outcome. Configuration will focus on the ignition/combustion tools.

=== Reliability
SLE Micro will recover automatically from issues occurring during package or update
installation.
This will be implemented using the snapshot/rollback functionality of BtrFS
combined with transactional updates.

